test_that("generic.f.test.R works", {
    # power.f.test -----------------------------------------------------------------------------------------------------
    crrOut <- capture.output(power.f.test(ncp = 2, df1 = 4, df2 = 100, alpha = 0.05, plot = FALSE))
    crrDtl <- capture.output(power.f.test(ncp = 2, df1 = 4, df2 = 100, alpha = 0.05, plot = FALSE, verbose = 2))
    crrPty <- capture.output(power.f.test(ncp = 2, df1 = 4, df2 = 100, alpha = 0.05, plot = FALSE, pretty = TRUE))
    crrPnD <- capture.output(power.f.test(ncp = 2, df1 = 4, df2 = 100, alpha = 0.05, plot = FALSE, verbose = 2, pretty = TRUE))
    expect_equal(power.f.test(ncp = 2, df1 = 4, df2 = 100, alpha = 0.05, plot = FALSE, verbose = 0),
                 list(power = 0.165090262, ncp = 2, null.ncp = 0, alpha = 0.05, df1 = 4, df2 = 100, f.alpha = 2.4626149))
    expect_equal(crrOut, c("+--------------------------------------------------+",
                           "|                POWER CALCULATION                 |",
                           "+--------------------------------------------------+", "",
                           "Generic F-Test", "",
                           "----------------------------------------------------",
                           "Hypotheses",
                           "----------------------------------------------------",
                           "  H0 (Null Claim) : ncp = 0",
                           "  H1 (Alt. Claim) : ncp > 0", "",
                           "----------------------------------------------------",
                           "Results",
                           "----------------------------------------------------",
                           "  Type 1 Error (alpha) = 0.050",
                           "  Type 2 Error (beta)  = 0.835",
                           "  Statistical Power    = 0.165  <<", ""))
    expect_equal(crrDtl, c("+--------------------------------------------------+",
                           "|                POWER CALCULATION                 |",
                           "+--------------------------------------------------+", "",
                           "Generic F-Test", "",
                           "----------------------------------------------------",
                           "Hypotheses",
                           "----------------------------------------------------",
                           "  H0 (Null Claim) : ncp = 0",
                           "  H1 (Alt. Claim) : ncp > 0", "",
                           "----------------------------------------------------",
                           "Key Parameters",
                           "----------------------------------------------------",
                           "  Num. Deg. of Freedom   = 4 ",
                           "  Denom. Deg. of Freedom = 100 ",
                           "  Non-centrality of Alt. = 2.000 ",
                           "  Non-centrality of Null = 0.000 ",
                           "  Critical Value         = 2.463 ", "",
                           "----------------------------------------------------",
                           "Results",
                           "----------------------------------------------------",
                           "  Type 1 Error (alpha) = 0.050",
                           "  Type 2 Error (beta)  = 0.835",
                           "  Statistical Power    = 0.165  <<", "",
                           "----------------------------------------------------",
                           "Definitions",
                           "----------------------------------------------------",
                           "  ncp      : Non-centrality parameter of alt. ",
                           "  null.ncp : Non-centrality parameter of null ", ""))
    expect_equal(crrPty, c("╔══════════════════════════════════════════════════╗",
                           "║               \033[34m POWER CALCULATION \033[0m                ║",
                           "╚══════════════════════════════════════════════════╝", "",
                           "Generic F-Test", "",
                           "────────────────────────────────────────────────────",
                           "Hypotheses",
                           "────────────────────────────────────────────────────",
                           "  H₀ (Null)         : λ = λ₀ ",
                           "  H₁ (Alternative)  : λ > λ₀ ", "",
                           "────────────────────────────────────────────────────",
                           "Results",
                           "────────────────────────────────────────────────────",
                           "  Type 1 Error (α)   = 0.050",
                           "  Type 2 Error (β)   = 0.835",
                           "  \033[34mStatistical Power  = 0.165\033[0m  \033[1;35m◄◄\033[0m", ""))
    expect_equal(crrPnD, c("╔══════════════════════════════════════════════════╗",
                           "║               \033[34m POWER CALCULATION \033[0m                ║",
                           "╚══════════════════════════════════════════════════╝", "",
                           "Generic F-Test", "",
                           "────────────────────────────────────────────────────",
                           "Hypotheses",
                           "────────────────────────────────────────────────────",
                           "  H₀ (Null)         : λ = λ₀ ",
                           "  H₁ (Alternative)  : λ > λ₀ ", "",
                           "────────────────────────────────────────────────────",
                           "Key Parameters",
                           "────────────────────────────────────────────────────",
                           "  df1               = 4",
                           "  df2               = 100",
                           "  λ                 = 2.000",
                           "  λ₀                 = 0.000",
                           "  F⁻¹(α, λ₀)          = 2.463 ", "",
                           "────────────────────────────────────────────────────",
                           "Results",
                           "────────────────────────────────────────────────────",
                           "  Type 1 Error (α)   = 0.050",
                           "  Type 2 Error (β)   = 0.835",
                           "  \033[34mStatistical Power  = 0.165\033[0m  \033[1;35m◄◄\033[0m", "",
                           "\033[36m────────────────────────────────────────────────────\033[0m",
                           "\033[36mDefinitions\033[0m",
                           "\033[36m────────────────────────────────────────────────────\033[0m",
                           "\033[36m  λ   : Non-centrality parameter under alternative",
                           "\033[0m\033[36m  λ₀ : Non-centrality parameter under null", "", "\033[0m"))

    expect_equal(power.f.test(ncp = 2, null.ncp = 1, df1 = 1, df2 = 100, alpha = 0.05, plot = FALSE, verbose = 0),
                 list(power = 0.107653633, ncp = 2, null.ncp = 1, alpha = 0.05, df1 = 1, df2 = 100, f.alpha = 7.19401376))

    expect_equal(power.f.test(ncp = 10, df1 = 2, df2 = 100, alpha = 0.05, plot = FALSE, verbose = 0),
                 list(power = 0.8029764, ncp = 10, null.ncp = 0, alpha = 0.05, df1 = 2, df2 = 100, f.alpha = 3.0872959))

    expect_error(power.f.test(ncp = 1, null.ncp = 11, df1 = 1, df2 = 100, alpha = 0.05, plot = FALSE, verbose = 0),
                 "`ncp` should be greater than or equal to `null.ncp`.")

})
