test_that("proportions.onetwo.R works", {
    # power.exact.oneprop ----------------------------------------------------------------------------------------------

    # power.z.oneprop (= pwrss.z.prop) ---------------------------------------------------------------------------------

    # power.exact.twoprops ---------------------------------------------------------------------------------------------

    # power.z.twoprops (= pwrss.z.2props) ------------------------------------------------------------------------------
    crrRes <- power.z.twoprops(prob1 = 0.65, prob2 = 0.60, alpha = 0.05, n2 = 500, alternative = "one.sided", verbose = 0)
    crrOut <- capture.output(power.z.twoprops(prob1 = 0.65, prob2 = 0.60, alpha = 0.05, n2 = 500, alternative = "one.sided"))
    crrDtl <- capture.output(power.z.twoprops(prob1 = 0.65, prob2 = 0.60, alpha = 0.05, n2 = 500, alternative = "one.sided", verbose = 2))
    crrPty <- capture.output(power.z.twoprops(prob1 = 0.65, prob2 = 0.60, alpha = 0.05, n2 = 500, alternative = "one.sided", pretty = TRUE))
    expect_equal(class(crrRes), c("pwrss", "z", "twoprops"))
    expect_equal(names(crrRes),
                 c("parms", "test", "delta", "odds.ratio", "mean", "sd", "null.mean", "null.sd", "z.alpha", "power", "n", "n.total"))
    expect_equal(crrRes[["parms"]],
                 list(prob1 = 0.65, prob2 = 0.6, margin = 0, n.ratio = 1, alpha = 0.05, alternative = "one.sided",
                      arcsine = FALSE, correct = FALSE, paired = FALSE, rho.paired = 0.5, std.error = "pooled",
                      ceiling = TRUE, verbose = 0, pretty = FALSE))
    expect_equal(crrRes[c("test", "delta", "odds.ratio", "mean", "sd", "null.mean", "null.sd", "z.alpha", "power", "n", "n.total")],
                 list(test = "z", delta = 0.05, odds.ratio = 1.23809524, mean = 1.63517485, sd = 1, null.mean = 0, null.sd = 1.001336,
                      z.alpha = 1.64705116, power = 0.495262149, n = c(n1 = 500, n2 = 500), n.total = 1000))
    expect_equal(crrOut, c("+--------------------------------------------------+",
                           "|                POWER CALCULATION                 |",
                           "+--------------------------------------------------+", "",
                           "Independent Proportions", "",
                           "  Method          : Normal Approximation", "",
                           "----------------------------------------------------",
                           "Hypotheses",
                           "----------------------------------------------------",
                           "  H0 (Null Claim) : prob1 - prob2 <= 0 ",
                           "  H1 (Alt. Claim) : prob1 - prob2 > 0 ", "",
                           "----------------------------------------------------",
                           "Results",
                           "----------------------------------------------------",
                           "  Sample Size          = 500 and 500",
                           "  Type 1 Error (alpha) = 0.050",
                           "  Type 2 Error (beta)  = 0.505",
                           "  Statistical Power    = 0.495  <<", ""))
    expect_equal(crrDtl, c("+--------------------------------------------------+",
                           "|                POWER CALCULATION                 |",
                           "+--------------------------------------------------+", "",
                           "Independent Proportions", "",
                           "  Method          : Normal Approximation", "",
                           "----------------------------------------------------",
                           "Hypotheses",
                           "----------------------------------------------------",
                           "  H0 (Null Claim) : prob1 - prob2 <= 0 ",
                           "  H1 (Alt. Claim) : prob1 - prob2 > 0 ", "",
                           "----------------------------------------------------",
                           "Key Parameters",
                           "----------------------------------------------------",
                           "  prob1 - prob2        = 0.050",
                           "  Odds Ratio           = 1.238",
                           "  Mean of Alt.         = 1.635",
                           "  Mean of Null         = 0",
                           "  Critical Value       = 1.647", "",
                           "----------------------------------------------------",
                           "Results",
                           "----------------------------------------------------",
                           "  Sample Size          = 500 and 500",
                           "  Type 1 Error (alpha) = 0.050",
                           "  Type 2 Error (beta)  = 0.505",
                           "  Statistical Power    = 0.495  <<", "",
                           "----------------------------------------------------",
                           "Definitions",
                           "----------------------------------------------------",
                           "  prob1       : Probability of success in the first group ",
                           "  prob2       : Probability of success in the second group ",
                           "  Odds Ratio  : Odds(prob1) / Odds(prob2) ",
                           "  Odds(prob1) : prob1 / (1 - prob1) ",
                           "  Odds(prob2) : prob2 / (1 - prob2) ", ""))
    expect_equal(crrPty, c("╔══════════════════════════════════════════════════╗",
                           "║               \033[34m POWER CALCULATION \033[0m                ║",
                           "╚══════════════════════════════════════════════════╝", "",
                           "Independent Proportions", "",
                           "  Method            : Normal Approximation", "",
                           "────────────────────────────────────────────────────",
                           "Hypotheses",
                           "────────────────────────────────────────────────────",
                           "  H₀ (Null)         : P₁ - P₂ ≤ 0 ",
                           "  H₁ (Alternative)  : P₁ - P₂ > 0 ", "",
                           "────────────────────────────────────────────────────",
                           "Results",
                           "────────────────────────────────────────────────────",
                           "  Sample Size       = 500 and 500",
                           "  Type 1 Error (α)  = 0.050",
                           "  Type 2 Error (β)  = 0.505",
                           "  \033[34mStatistical Power = 0.495\033[0m  \033[1;35m◄◄\033[0m", ""))
    # sample size
    crrRes <- power.z.twoprops(prob1 = 0.65, prob2 = 0.60, alpha = 0.05, power = 0.80, alternative = "one.sided", verbose = 0)
    crrOut <- capture.output(power.z.twoprops(prob1 = 0.65, prob2 = 0.60, alpha = 0.05, power = 0.80, alternative = "one.sided"))
    crrDtl <- capture.output(power.z.twoprops(prob1 = 0.65, prob2 = 0.60, alpha = 0.05, power = 0.80, alternative = "one.sided", verbose = 2))
    crrPty <- capture.output(power.z.twoprops(prob1 = 0.65, prob2 = 0.60, alpha = 0.05, power = 0.80, alternative = "one.sided", pretty = TRUE))
    expect_equal(class(crrRes), c("pwrss", "z", "twoprops"))
    expect_equal(names(crrRes),
                 c("parms", "test", "delta", "odds.ratio", "mean", "sd", "null.mean", "null.sd", "z.alpha", "power", "n", "n.total"))
    expect_equal(crrRes[["parms"]],
                 list(prob1 = 0.65, prob2 = 0.6, margin = 0, n.ratio = 1, alpha = 0.05, alternative = "one.sided",
                      arcsine = FALSE, correct = FALSE, paired = FALSE, rho.paired = 0.5, std.error = "pooled",
                      ceiling = TRUE, verbose = 0, pretty = FALSE))
    expect_equal(crrRes[c("test", "delta", "odds.ratio", "mean", "sd", "null.mean", "null.sd", "z.alpha", "power", "n", "n.total")],
                 list(test = "z", delta = 0.05, odds.ratio = 1.23809524, mean = 2.48955035, sd = 1, null.mean = 0, null.sd = 1.001336,
                      z.alpha = 1.64705116, power = 0.8002457, n = c(n1 = 1159, n2 = 1159), n.total = 2318))
    expect_equal(crrOut, c("+--------------------------------------------------+",
                           "|             SAMPLE SIZE CALCULATION              |",
                           "+--------------------------------------------------+", "",
                           "Independent Proportions", "",
                           "  Method          : Normal Approximation", "",
                           "----------------------------------------------------",
                           "Hypotheses",
                           "----------------------------------------------------",
                           "  H0 (Null Claim) : prob1 - prob2 <= 0 ",
                           "  H1 (Alt. Claim) : prob1 - prob2 > 0 ", "",
                           "----------------------------------------------------",
                           "Results",
                           "----------------------------------------------------",
                           "  Sample Size          = 1159 and 1159  <<",
                           "  Type 1 Error (alpha) = 0.050",
                           "  Type 2 Error (beta)  = 0.200",
                           "  Statistical Power    = 0.800", ""))
    expect_equal(crrDtl, c("+--------------------------------------------------+",
                           "|             SAMPLE SIZE CALCULATION              |",
                           "+--------------------------------------------------+", "",
                           "Independent Proportions", "",
                           "  Method          : Normal Approximation", "",
                           "----------------------------------------------------",
                           "Hypotheses",
                           "----------------------------------------------------",
                           "  H0 (Null Claim) : prob1 - prob2 <= 0 ",
                           "  H1 (Alt. Claim) : prob1 - prob2 > 0 ", "",
                           "----------------------------------------------------",
                           "Key Parameters",
                           "----------------------------------------------------",
                           "  prob1 - prob2        = 0.050",
                           "  Odds Ratio           = 1.238",
                           "  Mean of Alt.         = 2.490",
                           "  Mean of Null         = 0",
                           "  Critical Value       = 1.647", "",
                           "----------------------------------------------------",
                           "Results",
                           "----------------------------------------------------",
                           "  Sample Size          = 1159 and 1159  <<",
                           "  Type 1 Error (alpha) = 0.050",
                           "  Type 2 Error (beta)  = 0.200",
                           "  Statistical Power    = 0.800", "",
                           "----------------------------------------------------",
                           "Definitions",
                           "----------------------------------------------------",
                           "  prob1       : Probability of success in the first group ",
                           "  prob2       : Probability of success in the second group ",
                           "  Odds Ratio  : Odds(prob1) / Odds(prob2) ",
                           "  Odds(prob1) : prob1 / (1 - prob1) ",
                           "  Odds(prob2) : prob2 / (1 - prob2) ", ""))
    expect_equal(crrPty, c("╔══════════════════════════════════════════════════╗",
                           "║           \033[34m SAMPLE SIZE CALCULATION \033[0m              ║",
                           "╚══════════════════════════════════════════════════╝", "",
                           "Independent Proportions", "",
                           "  Method            : Normal Approximation", "",
                           "────────────────────────────────────────────────────",
                           "Hypotheses",
                           "────────────────────────────────────────────────────",
                           "  H₀ (Null)         : P₁ - P₂ ≤ 0 ",
                           "  H₁ (Alternative)  : P₁ - P₂ > 0 ", "",
                           "────────────────────────────────────────────────────",
                           "Results",
                           "────────────────────────────────────────────────────",
                           "  \033[34mSample Size       = 1159 and 1159\033[0m  \033[1;35m◄◄\033[0m",
                           "  Type 1 Error (α)  = 0.050",
                           "  Type 2 Error (β)  = 0.200",
                           "  Statistical Power = 0.800", ""))
})
