test_that("helper.R works", {
    # ensure verbose
    expect_equal(ensure.verbose(), 1)
    expect_equal(ensure.verbose("A"), 1)
    expect_equal(ensure.verbose(complex(1)), 1)
    expect_equal(ensure.verbose(-2), 1)
    expect_equal(ensure.verbose(-1), -1)
    expect_equal(ensure.verbose(0), 0)
    expect_equal(ensure.verbose(1), 1)
    expect_equal(ensure.verbose(2), 2)
    expect_equal(ensure.verbose(3), 1)
    expect_equal(ensure.verbose(-2L), 1)
    expect_equal(ensure.verbose(-1L), -1)
    expect_equal(ensure.verbose(0L), 0)
    expect_equal(ensure.verbose(1L), 1)
    expect_equal(ensure.verbose(2L), 2)
    expect_equal(ensure.verbose(3L), 1)
    expect_equal(ensure.verbose(FALSE), 0)
    expect_equal(ensure.verbose(TRUE), 1)
})
