test_that("generic.binom.test.R works", {
    # power.binom.test -------------------------------------------------------------------------------------------------
    crrOut <- capture.output(power.binom.test(size = 200, prob = 0.6, null.prob = 0.5, alpha = 0.05, alternative = "one.sided",
                                              plot = FALSE))
    crrDtl <- capture.output(power.binom.test(size = 200, prob = 0.6, null.prob = 0.5, alpha = 0.05, alternative = "one.sided",
                                              plot = FALSE, verbose = 2))
    crrPty <- capture.output(power.binom.test(size = 200, prob = 0.6, null.prob = 0.5, alpha = 0.05, alternative = "one.sided",
                                              plot = FALSE, pretty = TRUE))
    crrPnD <- capture.output(power.binom.test(size = 200, prob = 0.6, null.prob = 0.5, alpha = 0.05, alternative = "one.sided",
                                              plot = FALSE, verbose = 2, pretty = TRUE))
    expect_equal(power.binom.test(size = 200, prob = 0.6, null.prob = 0.5, alpha = 0.05, alternative = "one.sided", plot = FALSE,
                                  verbose = 0),
                 list(size = 200, alpha = 0.038418816, alternative = "one.sided", prob = 0.6, null.prob = 0.5,
                              binom.alpha = 112, power = 0.860335667))
    expect_equal(crrOut, c("+--------------------------------------------------+",
                           "|                POWER CALCULATION                 |",
                           "+--------------------------------------------------+", "",
                           "Generic Binomial Test", "",
                           "----------------------------------------------------",
                           "Hypotheses",
                           "----------------------------------------------------",
                           "  H0 (Null Claim) : prob <= null.prob",
                           "  H1 (Alt. Claim) : prob  > null.prob", "",
                           "----------------------------------------------------",
                           "Results",
                           "----------------------------------------------------",
                           "  Type 1 Error (alpha) = 0.038",
                           "  Type 2 Error (beta)  = 0.140",
                           "  Statistical Power    = 0.860  <<", ""))
    expect_equal(crrDtl, c("+--------------------------------------------------+",
                           "|                POWER CALCULATION                 |",
                           "+--------------------------------------------------+", "",
                           "Generic Binomial Test", "",
                           "----------------------------------------------------",
                           "Hypotheses",
                           "----------------------------------------------------",
                           "  H0 (Null Claim) : prob <= null.prob",
                           "  H1 (Alt. Claim) : prob  > null.prob", "",
                           "----------------------------------------------------",
                           "Key Parameters",
                           "----------------------------------------------------",
                           "  Size                   = 200",
                           "  Probability Under Alt. = 0.600",
                           "  Probability Under Null = 0.5",
                           "  Critical Value         = 112", "",
                           "----------------------------------------------------",
                           "Results",
                           "----------------------------------------------------",
                           "  Type 1 Error (alpha) = 0.038",
                           "  Type 2 Error (beta)  = 0.140",
                           "  Statistical Power    = 0.860  <<", "",
                           "----------------------------------------------------",
                           "Definitions",
                           "----------------------------------------------------",
                           "  prob      : Probability under alt. ",
                           "  null.prob : Probability under null ", ""))
    expect_equal(crrPty, c("╔══════════════════════════════════════════════════╗",
                           "║               \033[34m POWER CALCULATION \033[0m                ║",
                           "╚══════════════════════════════════════════════════╝", "",
                           "Generic Binomial Test", "",
                           "────────────────────────────────────────────────────",
                           "Hypotheses",
                           "────────────────────────────────────────────────────",
                           "  H₀ (Null)         : P ≤ P₀ ",
                           "  H₁ (Alternative)  : P > P₀ ", "",
                           "────────────────────────────────────────────────────",
                           "Results",
                           "────────────────────────────────────────────────────",
                           "  Type 1 Error (α)   = 0.038",
                           "  Type 2 Error (β)   = 0.140",
                           "  \033[34mStatistical Power  = 0.860\033[0m  \033[1;35m◄◄\033[0m", ""))
    expect_equal(crrPnD, c("╔══════════════════════════════════════════════════╗",
                           "║               \033[34m POWER CALCULATION \033[0m                ║",
                           "╚══════════════════════════════════════════════════╝", "",
                           "Generic Binomial Test", "",
                           "────────────────────────────────────────────────────",
                           "Hypotheses",
                           "────────────────────────────────────────────────────",
                           "  H₀ (Null)         : P ≤ P₀ ",
                           "  H₁ (Alternative)  : P > P₀ ", "",
                           "────────────────────────────────────────────────────",
                           "Key Parameters",
                           "────────────────────────────────────────────────────",
                           "  Size              = 200 ",
                           "  P                 = 0.600 ",
                           "  P₀                 = 0.5 ",
                           "  Bin⁻¹(α, P₀)        = 112 ", "",
                           "────────────────────────────────────────────────────",
                           "Results",
                           "────────────────────────────────────────────────────",
                           "  Type 1 Error (α)   = 0.038",
                           "  Type 2 Error (β)   = 0.140",
                           "  \033[34mStatistical Power  = 0.860\033[0m  \033[1;35m◄◄\033[0m", "",
                           "\033[36m────────────────────────────────────────────────────\033[0m",
                           "\033[36mDefinitions\033[0m",
                           "\033[36m────────────────────────────────────────────────────\033[0m",
                           "\033[36m  P   : Probability under alternative",
                           "\033[0m\033[36m  P₀ : Probability under null", "", "\033[0m"))

    expect_equal(power.binom.test(size = 200, prob = 0.4, null.prob = 0.5, alpha = 0.05, alternative = "two.sided",
                                  plot = FALSE, verbose = 0),
                 list(size = 200, alpha = 0.040037192, alternative = "two.sided", prob = 0.4, null.prob = 0.5,
                      binom.alpha = c(85, 114), power = 0.786848265))

    expect_equal(power.binom.test(size = 200, prob = 0.5, null.prob = c(0.4, 0.6), alpha = 0.05, alternative = "two.one.sided",
                                  plot = FALSE, verbose = 0),
                 list(size = 200, alpha = 0.049184711, alternative = "two.one.sided", prob = 0.5, null.prob = c(0.4, 0.6),
                      binom.alpha = c(91, 108), power = 0.7707534))

    expect_equal(power.binom.test(size = 200, prob = 0.7, null.prob = c(0.4, 0.6), alpha = 0.05, alternative = "two.one.sided",
                                  plot = FALSE, verbose = 0),
                 list(size = 200, alpha = 0.049432239, alternative = "two.one.sided", prob = 0.7, null.prob = c(0.4, 0.6),
                      binom.alpha = c(66, 133), power = 0.84208844))

    expect_error(power.binom.test(size = 200, prob = 0.6, null.prob = c(0.5, 0.7), alpha = 0.05, alternative = "one.sided",
                                  plot = FALSE, verbose = 0),
                 "If `alternative` is \"two.sided\" or \"one.sided\", `null.prob` must be of length one.")
    expect_error(power.binom.test(size = -1, prob = 0.6, null.prob = 0.5, alpha = 0.05, alternative = "one.sided", plot = FALSE, verbose = 0),
                 "Argument `size` does not have a valid value \\(integer-like, >= 0, and finite\\).")
    expect_error(power.binom.test(size = 2, prob = 0.6, null.prob = 0.5, alpha = 0.05, alternative = "two.one.sided", plot = FALSE),
                 paste("If `alternative` is \"two.one.sided\", `null.prob` must be of length two \\(lower and upper bounds,",
                       "with the upper bound being larger than the lower bound\\)."))
    expect_error(power.binom.test(size = 2, prob = 0.6, null.prob = c(0.5, 0.3), alpha = 0.05, alternative = "two.one.sided", plot = FALSE),
                 paste("If `alternative` is \"two.one.sided\", `null.prob` must be of length two \\(lower and upper bounds,",
                       "with the upper bound being larger than the lower bound\\)."))
})
